//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.18 at 07:40:02 PM MSK 
//


package com.eugene.wsdemo.domain;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.eugene.wsdemo.domain package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.eugene.wsdemo.domain
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetAllCountriesRequest }
     * 
     */
    public GetAllCountriesRequest createGetAllCountriesRequest() {
        return new GetAllCountriesRequest();
    }

    /**
     * Create an instance of {@link CreateCountryRequest }
     * 
     */
    public CreateCountryRequest createCreateCountryRequest() {
        return new CreateCountryRequest();
    }

    /**
     * Create an instance of {@link Country }
     * 
     */
    public Country createCountry() {
        return new Country();
    }

    /**
     * Create an instance of {@link DeleteCountryRequest }
     * 
     */
    public DeleteCountryRequest createDeleteCountryRequest() {
        return new DeleteCountryRequest();
    }

    /**
     * Create an instance of {@link GetAllCountriesResponse }
     * 
     */
    public GetAllCountriesResponse createGetAllCountriesResponse() {
        return new GetAllCountriesResponse();
    }

    /**
     * Create an instance of {@link GetCountryByNameRequest }
     * 
     */
    public GetCountryByNameRequest createGetCountryByNameRequest() {
        return new GetCountryByNameRequest();
    }

    /**
     * Create an instance of {@link GetCountryResponse }
     * 
     */
    public GetCountryResponse createGetCountryResponse() {
        return new GetCountryResponse();
    }

    /**
     * Create an instance of {@link UpdateCountryRequest }
     * 
     */
    public UpdateCountryRequest createUpdateCountryRequest() {
        return new UpdateCountryRequest();
    }

}
